# -*- coding: utf-8 -*-
"""BILLIONAIRES ANALYSIS EDA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12hd-vEUPPDaI9X60L2El61H6qCdxDndg
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sbn

from google.colab import files
up  = files.upload()

df = pd.read_csv('Forbes Billionaire.csv',encoding= 'unicode_escape')

df.head()

df.describe()

df.info()

df.isna().sum()

#histogram plot
plt.figure(figsize=(20,10))
sbn.histplot(x='Networth',hue='Source',data=df)
plt.show()

plt.figure(figsize=(20,10))

sbn.histplot(x='Age',data=df)
plt.show()

a = df['Industry'].value_counts().head()
a

Index=a.index
Index

Values=a.values
Values

plt.figure(figsize=(5,5))
plt.pie(Values,labels=Index)
plt.title('5 category',fontsize=20)
plt.show()

b = df['Country'].value_counts().head()
b

Index1 = b.index
Index1

Value1 = b.values
Value1

plt.figure(figsize=(5,5))
plt.pie(Value1,labels=Index1,colors=['red','Pink','blue','Orange','Yellow'])
plt.title('5 Country',fontsize=20)
plt.show()

c = df['Source'].value_counts().head()
c
Index2 = c.index
Index2
Value2 = c.values
Value2
plt.figure(figsize=(8,5))
plt.bar(Index2,Value2,color='#B266FF')
plt.title('Source',fontsize=20,color='#6600CC')
plt.show()

d = df['Industry'].value_counts().head()
d
Index3 = d.index
Index3
Value3 = d.values
Value3
plt.figure(figsize=(10,5))
plt.bar(Index3,Value3)
plt.title('Industry',fontsize=20)
plt.show()

e = df['Age'].value_counts().head()
e
Index4 = e.index
Index4
Value4 = e.values
Value4
plt.figure(figsize=(10,5))
plt.bar(Index4,Value4,color=['red','green','orange','yellow','blue'])
plt.title('Most Billionaires Age Category',fontsize=20)
plt.show()

